#!/usr/bin/env bash
# =============================================================================
# render-portainer-stacks.sh — split the unified tree into ONE editable stack
# per group, as Git-stack artifacts for Portainer (mode B).
# =============================================================================
# The platform normally deploys as ONE swarm stack (deploy.sh → industream-prod,
# 45 services). A CLI-deployed stack is "external/limited" in Portainer: viewable
# per-service (mode A) but NOT editable (Portainer has no source file).
#
# This generator emits one self-contained, EDITABLE compose file per group so
# Portainer can OWN each as a Git stack pointing at its subfolder:
#
#   releases/portainer/<env>-<edition>/
#     core/docker-compose.yml          (+ Logto + hub EE transform when edition=ee)
#     flowmaker/docker-compose.yml
#     datacatalog/docker-compose.yml
#     data/docker-compose.yml
#     monitoring/docker-compose.yml
#     workers/docker-compose.yml        (CE socle + selected community workers)
#     workers-premium/docker-compose.yml (ee only)
#     timescale/docker-compose.yml      (ee only)
#     portainer/docker-compose.yml
#     .env                              (shared, auto-loaded by Portainer/compose)
#     bootstrap.sh                      (pre-create the external shared network)
#     README.md
#
# Files are MERGED (base + runtime/swarm overlay) but NOT interpolated — the
# ${VARS} stay templated and resolve from the sibling .env (so the same artifact
# is editable in Portainer's editor and re-renderable from source). The shared
# `platform` overlay network is rewritten to `external: true` (every group stack
# attaches to the one pre-created ${ENV}-platform instead of each creating it).
#
#   ./render-portainer-stacks.sh --env prod --edition ee [--bundle 1.0.1] \
#       [--workers "worker-timer,worker-…"] [--with-portainer]
# =============================================================================
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"   # unified/
cd "$HERE"

ENV="prod" EDITION="ce" BUNDLE="" WORKERS_ENABLED="" WITH_PORTAINER=false BAKED=false
RUNTIME="swarm"   # mode A/B target is swarm; compose split is a later step
while [[ $# -gt 0 ]]; do
  case "$1" in
    --env)            ENV="$2"; shift 2 ;;
    --edition)        EDITION="$2"; shift 2 ;;
    --bundle)         BUNDLE="$2"; shift 2 ;;
    --workers)        WORKERS_ENABLED="$2"; shift 2 ;;
    --with-portainer) WITH_PORTAINER=true; shift ;;
    # --baked: interpolate every ${VAR} to a literal value (self-contained files,
    # no sibling .env needed by Portainer). Default keeps ${VARS} templated.
    --baked)          BAKED=true; shift ;;
    -h|--help)        sed -n '2,34p' "$0" | sed 's/^# \{0,1\}//'; exit 0 ;;
    *) echo "Unknown option: $1" >&2; exit 1 ;;
  esac
done
[[ "$EDITION" == ce || "$EDITION" == ee ]] || { echo "✗ --edition ce|ee" >&2; exit 1; }

# ---- group set per edition (matches deploy.sh's GROUP_SET semantics) --------
GROUP_LIST="core flowmaker datacatalog data monitoring workers"
[[ "$EDITION" == ee ]] && GROUP_LIST="$GROUP_LIST workers-premium timescale"
[[ "$WITH_PORTAINER" == true ]] && GROUP_LIST="$GROUP_LIST portainer"

# ---- resolve the release bundle (same rule as deploy.sh) --------------------
if [[ -n "$BUNDLE" ]]; then
  BUNDLE_DIR="releases/bundle-platform-${BUNDLE}"
else
  mapfile -t _b < <(ls -d releases/bundle-platform-*/ 2>/dev/null)
  [[ ${#_b[@]} -eq 1 ]] || { echo "✗ pass --bundle <ver> (found ${#_b[@]} bundles)" >&2; exit 1; }
  BUNDLE_DIR="${_b[0]%/}"
fi
[[ -d "$BUNDLE_DIR" ]] || { echo "✗ no bundle at ${BUNDLE_DIR}" >&2; exit 1; }

# ---- --baked: the env-file chain to interpolate from (same order as deploy.sh) -
ENV_FILES=()
if [[ "$BAKED" == true ]]; then
  export ENV   # ${ENV}-platform etc. interpolate from the environment
  ENV_FILES=(--env-file registries.env --env-file versions.env --env-file auth.env --env-file "runtime.${RUNTIME}.env")
  for bf in "$BUNDLE_DIR"/.env.*; do ENV_FILES+=(--env-file "$bf"); done
  [[ -f ".env.${ENV}" ]] && ENV_FILES+=(--env-file ".env.${ENV}")
fi

OUT="releases/portainer/${ENV}-${EDITION}"
rm -rf "$OUT"; mkdir -p "$OUT"

# ---- the shared .env (concatenated single sources; later wins, as deploy.sh) -
# Non-secret only: image refs, versions, domain, registries. Secrets stay
# EXTERNAL (created once by create-secrets.sh) and never land in a Git artifact.
ENVOUT="$OUT/.env"
{
  echo "# Generated by render-portainer-stacks.sh — env=${ENV} edition=${EDITION}"
  echo "# Auto-loaded by Portainer/compose from each stack folder. NO SECRETS here."
  echo "ENV=${ENV}"
  for f in registries.env versions.env auth.env "runtime.${RUNTIME}.env"; do
    [[ -f "$f" ]] && { echo "# --- $f ---"; grep -vE '^\s*(#|$)' "$f" || true; }
  done
  for bf in "$BUNDLE_DIR"/.env.*; do echo "# --- ${bf##*/} ---"; grep -vE '^\s*(#|$)' "$bf" || true; done
  [[ -f ".env.${ENV}" ]] && { echo "# --- .env.${ENV} ---"; grep -vE '^\s*(#|$)' ".env.${ENV}" || true; }
} > "$ENVOUT"

echo "▶ rendering ${EDITION^^} / env=${ENV} → ${OUT}  groups=[${GROUP_LIST}]"

# ---- per-group merge -> external-network rewrite ----------------------------
for g in $GROUP_LIST; do
  files=(-f "base/${g}.yml")
  [[ -f "runtime/${RUNTIME}/${g}.yml" ]] && files+=(-f "runtime/${RUNTIME}/${g}.yml")
  # datacatalog increment-1 top-level overlay rides with the datacatalog group.
  [[ "$g" == datacatalog && -f "runtime.${RUNTIME}.yml" ]] && files+=(-f "runtime.${RUNTIME}.yml")
  # EE transform (hub-backend/frontend swap + Logto + logto-postgres) lands in the
  # CORE stack — that is where industream-hub-backend/frontend live.
  if [[ "$g" == core && "$EDITION" == ee ]]; then
    files+=(-f "base/ee.yml")
    [[ -f "runtime/${RUNTIME}/ee.yml" ]] && files+=(-f "runtime/${RUNTIME}/ee.yml")
  fi

  mkdir -p "$OUT/$g"
  # Merge overlays WITHOUT interpolation (keep ${VARS} templated), then rewrite
  # the shared `platform` overlay network to external. We write the merged config
  # to a temp file (NOT a pipe): `python3 - <<'PY'` reads its PROGRAM from stdin,
  # which would swallow piped input — so the merge goes through argv, not stdin.
  _merged="$(mktemp)"
  if [[ "$BAKED" == true ]]; then
    docker compose "${ENV_FILES[@]}" "${files[@]}" config > "$_merged" 2>/dev/null
  else
    docker compose "${files[@]}" config --no-interpolate > "$_merged" 2>/dev/null
  fi
  WORKERS_CSV="$WORKERS_ENABLED" GROUP="$g" python3 - "$_merged" "$OUT/$g/docker-compose.yml" <<'PY'
import os, sys, yaml
src, out = sys.argv[1], sys.argv[2]
doc = yaml.safe_load(open(src)) or {}
doc.pop("name", None)            # drop the synthetic compose project name

# platform network: external so each group stack attaches to the ONE pre-created
# ${ENV}-platform instead of every stack trying to create it (2nd would clash).
nets = doc.get("networks") or {}
if "platform" in nets:
    # keep whatever name the merge produced (templated ${ENV}-platform, or a baked
    # literal like prod-platform) — just flip it to external + drop driver/attachable.
    existing_name = nets["platform"].get("name", "${ENV}-platform")
    nets["platform"] = {"external": True, "name": existing_name}
doc["networks"] = nets

# optional per-worker selection (workers / workers-premium groups only)
keep = {w.strip() for w in os.environ.get("WORKERS_CSV", "").split(",") if w.strip()}
if keep and os.environ.get("GROUP", "") in ("workers", "workers-premium"):
    svcs = doc.get("services") or {}
    doc["services"] = {n: s for n, s in svcs.items() if n in keep}

yaml.safe_dump(doc, open(out, "w"), sort_keys=False, default_flow_style=False)
PY
  rm -f "$_merged"
  # a sibling .env in every group folder (Portainer git-stack loads the .env next
  # to the compose file it deploys).
  cp "$ENVOUT" "$OUT/$g/.env"
  svc_count=$(python3 -c "import yaml;print(len((yaml.safe_load(open('$OUT/$g/docker-compose.yml')) or {}).get('services') or {}))")
  echo "  ✓ ${g}  (${svc_count} services)"
done

# ---- bootstrap: pre-create the external shared overlay network --------------
cat > "$OUT/bootstrap.sh" <<EOF
#!/usr/bin/env bash
# Pre-create the shared overlay network every group stack attaches to, and the
# external secrets, BEFORE deploying the per-group stacks in Portainer.
set -euo pipefail
ENV="\${1:-${ENV}}"
docker network inspect "\${ENV}-platform" >/dev/null 2>&1 \\
  || docker network create -d overlay --attachable "\${ENV}-platform"
echo "✓ network \${ENV}-platform ready"
echo "→ now run create-secrets.sh (external prod_* secrets), then add each"
echo "  subfolder here as a Portainer Git stack (Repository → Compose path = <group>/docker-compose.yml)."
EOF
chmod +x "$OUT/bootstrap.sh"

# ---- README: the GitOps flow ------------------------------------------------
cat > "$OUT/README.md" <<EOF
# Portainer per-group stacks — ${ENV} / ${EDITION^^}

One editable stack per group (mode B). Generated by
\`scripts/render-portainer-stacks.sh --env ${ENV} --edition ${EDITION}\`.

## Deploy order
1. \`./bootstrap.sh\`            — create the external \`${ENV}-platform\` overlay
2. \`scripts/setup/create-secrets.sh\` — create the external \`${ENV}_*\` secrets
3. In Portainer → **Stacks → Add stack → Git repository**, add one stack per
   subfolder (Compose path = \`<group>/docker-compose.yml\`). Each is then
   editable in the UI and redeployable from Git.

## Groups
$(for g in $GROUP_LIST; do echo "- \`$g/\`"; done)

> Edits made in the Portainer editor are NOT pushed back to Git — keep Git the
> source of truth and re-render to avoid drift.
EOF

echo "▶ done → ${OUT}  (bootstrap.sh + README.md + ${ENV}/.env)"
