services:
  equation-solver:
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 128M
        reservations:
          cpus: '0.03'
          memory: 64M
      restart_policy:
        condition: any
        delay: 10s
        window: 120s
    environment:
      FM_CDN_REGISTRY_URL: ${CDN_REGISTRY_URL:-http://cdn-server:4873}
      FM_DATACATALOG_URL: ${DATACATALOG_URL:-http://datacatalog-api:8080}
      FM_ROUTER_TRANSPORT_ADDRESS: tcp://*:5560
      FM_RUNTIME_HTTP_ADDRESS: http://flowmaker-scheduler:3120
      FM_WORKER_ID: worker-eqsolver001
      FM_WORKER_LOG_SOCKET_IO_ENDPOINT: http://flowmaker-logging:3000
      FM_WORKER_TRANSPORT_ADV_ADDRESS: tcp://equation-solver:5560
    healthcheck:
      test:
      - NONE
    image: ${WORKER_EQUATION_SOLVER_IMAGE}
    networks:
      platform: null
  worker-conditional-validator:
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 128M
        reservations:
          cpus: '0.03'
          memory: 64M
      restart_policy:
        condition: any
        delay: 10s
        window: 120s
    environment:
      FM_CDN_REGISTRY_URL: ${CDN_REGISTRY_URL:-http://cdn-server:4873}
      FM_DATACATALOG_URL: ${DATACATALOG_URL:-http://datacatalog-api:8080}
      FM_ROUTER_TRANSPORT_ADDRESS: tcp://*:5560
      FM_RUNTIME_HTTP_ADDRESS: http://flowmaker-scheduler:3120
      FM_WORKER_ID: worker-conditional-validator001
      FM_WORKER_LOG_SOCKET_IO_ENDPOINT: http://flowmaker-logging:3000
      FM_WORKER_TRANSPORT_ADV_ADDRESS: tcp://worker-conditional-validator:5560
    healthcheck:
      test:
      - NONE
    image: ${WORKER_CONDITIONAL_DATASET_VALIDATOR_IMAGE}
    networks:
      platform: null
  worker-data-logger:
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 128M
        reservations:
          cpus: '0.03'
          memory: 64M
      restart_policy:
        condition: any
        delay: 10s
        window: 120s
    environment:
      FM_CDN_REGISTRY_URL: ${CDN_REGISTRY_URL:-http://cdn-server:4873}
      FM_DATACATALOG_URL: ${DATACATALOG_URL:-http://datacatalog-api:8080}
      FM_ROUTER_TRANSPORT_ADDRESS: tcp://*:5560
      FM_RUNTIME_HTTP_ADDRESS: http://flowmaker-scheduler:3120
      FM_WORKER_ID: worker-data-logger001
      FM_WORKER_LOG_SOCKET_IO_ENDPOINT: http://flowmaker-logging:3000
      FM_WORKER_TRANSPORT_ADV_ADDRESS: tcp://worker-data-logger:5560
    healthcheck:
      test:
      - NONE
    image: ${WORKER_DATA_LOGGER_IMAGE}
    networks:
      platform: null
  worker-datacatalog-mapper:
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 256M
        reservations:
          cpus: '0.03'
          memory: 128M
      restart_policy:
        condition: any
        delay: 10s
        window: 120s
    environment:
      FM_CDN_REGISTRY_URL: ${CDN_REGISTRY_URL:-http://cdn-server:4873}
      FM_DATACATALOG_URL: ${DATACATALOG_URL:-http://datacatalog-api:8080}
      FM_ROUTER_TRANSPORT_ADDRESS: tcp://*:5560
      FM_RUNTIME_HTTP_ADDRESS: http://flowmaker-scheduler:3120
      FM_WORKER_ID: worker-datacatalog-mapper001
      FM_WORKER_LOG_SOCKET_IO_ENDPOINT: http://flowmaker-logging:3000
      FM_WORKER_TRANSPORT_ADV_ADDRESS: tcp://worker-datacatalog-mapper:5560
    healthcheck:
      test:
      - NONE
    image: ${WORKER_DATACATALOG_MAPPER_IMAGE}
    networks:
      platform: null
  worker-enqueue:
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 128M
        reservations:
          cpus: '0.03'
          memory: 64M
      restart_policy:
        condition: any
        delay: 10s
        window: 120s
    environment:
      FM_CDN_REGISTRY_URL: ${CDN_REGISTRY_URL:-http://cdn-server:4873}
      FM_DATACATALOG_URL: ${DATACATALOG_URL:-http://datacatalog-api:8080}
      FM_ROUTER_TRANSPORT_ADDRESS: tcp://*:5560
      FM_RUNTIME_HTTP_ADDRESS: http://flowmaker-scheduler:3120
      FM_WORKER_ID: worker-js-enqueue001
      FM_WORKER_LOG_SOCKET_IO_ENDPOINT: http://flowmaker-logging:3000
      FM_WORKER_TRANSPORT_ADV_ADDRESS: tcp://worker-enqueue:5560
    healthcheck:
      test:
      - NONE
    image: ${WORKER_ENQUEUE_IMAGE}
    networks:
      platform: null
  worker-http-client:
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 128M
        reservations:
          cpus: '0.03'
          memory: 64M
      restart_policy:
        condition: any
        delay: 10s
        window: 120s
    environment:
      FM_CDN_REGISTRY_URL: ${CDN_REGISTRY_URL:-http://cdn-server:4873}
      FM_DATACATALOG_URL: ${DATACATALOG_URL:-http://datacatalog-api:8080}
      FM_ROUTER_TRANSPORT_ADDRESS: tcp://*:5560
      FM_RUNTIME_HTTP_ADDRESS: http://flowmaker-scheduler:3120
      FM_WORKER_ID: worker-http-client001
      FM_WORKER_LOG_SOCKET_IO_ENDPOINT: http://flowmaker-logging:3000
      FM_WORKER_TRANSPORT_ADV_ADDRESS: tcp://worker-http-client:5560
    healthcheck:
      test:
      - NONE
    image: ${WORKER_HTTP_IMAGE}
    networks:
      platform: null
  worker-influx-client-dc:
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 128M
        reservations:
          cpus: '0.03'
          memory: 64M
      restart_policy:
        condition: any
        delay: 10s
        window: 120s
    environment:
      FM_CDN_REGISTRY_URL: ${CDN_REGISTRY_URL:-http://cdn-server:4873}
      FM_DATACATALOG_URL: ${DATACATALOG_URL:-http://datacatalog-api:8080}
      FM_ROUTER_TRANSPORT_ADDRESS: tcp://*:5560
      FM_RUNTIME_HTTP_ADDRESS: http://flowmaker-scheduler:3120
      FM_WORKER_ID: worker-influx-client-dc001
      FM_WORKER_LOG_SOCKET_IO_ENDPOINT: http://flowmaker-logging:3000
      FM_WORKER_TRANSPORT_ADV_ADDRESS: tcp://worker-influx-client-dc:5560
    healthcheck:
      test:
      - NONE
    image: ${WORKER_INFLUX_CLIENT_IMAGE}
    networks:
      platform: null
  worker-js-expression:
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 128M
        reservations:
          cpus: '0.03'
          memory: 64M
      restart_policy:
        condition: any
        delay: 10s
        window: 120s
    environment:
      FM_CDN_REGISTRY_URL: ${CDN_REGISTRY_URL:-http://cdn-server:4873}
      FM_CDN_URL: ${CDN_URL:-http://cdn-cache:8080}
      FM_DATACATALOG_URL: ${DATACATALOG_URL:-http://datacatalog-api:8080}
      FM_ROUTER_TRANSPORT_ADDRESS: tcp://*:5560
      FM_RUNTIME_HTTP_ADDRESS: http://flowmaker-scheduler:3120
      FM_WORKER_ID: worker-js-expression001
      FM_WORKER_LOG_SOCKET_IO_ENDPOINT: http://flowmaker-logging:3000
      FM_WORKER_TRANSPORT_ADV_ADDRESS: tcp://worker-js-expression:5560
    healthcheck:
      test:
      - NONE
    image: ${WORKER_JS_EXPRESSION_IMAGE}
    networks:
      platform: null
  worker-modbus-tcp:
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 128M
        reservations:
          cpus: '0.03'
          memory: 64M
      restart_policy:
        condition: any
        delay: 10s
        window: 120s
    environment:
      FM_CDN_REGISTRY_URL: ${CDN_REGISTRY_URL:-http://cdn-server:4873}
      FM_DATACATALOG_URL: ${DATACATALOG_URL:-http://datacatalog-api:8080}
      FM_ROUTER_TRANSPORT_ADDRESS: tcp://*:5560
      FM_RUNTIME_HTTP_ADDRESS: http://flowmaker-scheduler:3120
      FM_WORKER_ID: worker-modbus-tcp001
      FM_WORKER_LOG_SOCKET_IO_ENDPOINT: http://flowmaker-logging:3000
      FM_WORKER_TRANSPORT_ADV_ADDRESS: tcp://worker-modbus-tcp:5560
    healthcheck:
      test:
      - NONE
    image: ${WORKER_MODBUS_TCP_IMAGE}
    networks:
      platform: null
  worker-mqtt-client:
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 128M
        reservations:
          cpus: '0.03'
          memory: 64M
      restart_policy:
        condition: any
        delay: 10s
        window: 120s
    environment:
      FM_CDN_REGISTRY_URL: ${CDN_REGISTRY_URL:-http://cdn-server:4873}
      FM_DATACATALOG_URL: ${DATACATALOG_URL:-http://datacatalog-api:8080}
      FM_ROUTER_TRANSPORT_ADDRESS: tcp://*:5560
      FM_RUNTIME_HTTP_ADDRESS: http://flowmaker-scheduler:3120
      FM_WORKER_ID: worker-mqtt-client001
      FM_WORKER_LOG_SOCKET_IO_ENDPOINT: http://flowmaker-logging:3000
      FM_WORKER_TRANSPORT_ADV_ADDRESS: tcp://worker-mqtt-client:5560
    healthcheck:
      test:
      - NONE
    image: ${WORKER_MQTT_CLIENT_IMAGE}
    networks:
      platform: null
  worker-notifications:
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 128M
        reservations:
          cpus: '0.03'
          memory: 64M
      restart_policy:
        condition: any
        delay: 10s
        window: 120s
    environment:
      FM_CDN_REGISTRY_URL: ${CDN_REGISTRY_URL:-http://cdn-server:4873}
      FM_DATACATALOG_URL: ${DATACATALOG_URL:-http://datacatalog-api:8080}
      FM_ROUTER_TRANSPORT_ADDRESS: tcp://*:5560
      FM_RUNTIME_HTTP_ADDRESS: http://flowmaker-scheduler:3120
      FM_WORKER_ID: worker-notifications001
      FM_WORKER_LOG_SOCKET_IO_ENDPOINT: http://flowmaker-logging:3000
      FM_WORKER_TRANSPORT_ADV_ADDRESS: tcp://worker-notifications:5560
    healthcheck:
      test:
      - NONE
    image: ${WORKER_NOTIFICATIONS_IMAGE}
    networks:
      platform: null
  worker-postgres-client:
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 128M
        reservations:
          cpus: '0.03'
          memory: 64M
      restart_policy:
        condition: any
        delay: 10s
        window: 120s
    environment:
      FM_CDN_REGISTRY_URL: ${CDN_REGISTRY_URL:-http://cdn-server:4873}
      FM_DATACATALOG_URL: ${DATACATALOG_URL:-http://datacatalog-api:8080}
      FM_ROUTER_TRANSPORT_ADDRESS: tcp://*:5560
      FM_RUNTIME_HTTP_ADDRESS: http://flowmaker-scheduler:3120
      FM_WORKER_ID: worker-postgres-client001
      FM_WORKER_LOG_SOCKET_IO_ENDPOINT: http://flowmaker-logging:3000
      FM_WORKER_TRANSPORT_ADV_ADDRESS: tcp://worker-postgres-client:5560
    healthcheck:
      test:
      - NONE
    image: ${WORKER_POSTGRES_CLIENT_IMAGE}
    networks:
      platform: null
  worker-test-data-generator:
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 128M
        reservations:
          cpus: '0.03'
          memory: 64M
      restart_policy:
        condition: any
        delay: 10s
        window: 120s
    environment:
      FM_CDN_REGISTRY_URL: ${CDN_REGISTRY_URL:-http://cdn-server:4873}
      FM_DATACATALOG_URL: ${DATACATALOG_URL:-http://datacatalog-api:8080}
      FM_ROUTER_TRANSPORT_ADDRESS: tcp://*:5560
      FM_RUNTIME_HTTP_ADDRESS: http://flowmaker-scheduler:3120
      FM_WORKER_ID: worker-test-data-generator001
      FM_WORKER_LOG_SOCKET_IO_ENDPOINT: http://flowmaker-logging:3000
      FM_WORKER_TRANSPORT_ADV_ADDRESS: tcp://worker-test-data-generator:5560
    healthcheck:
      test:
      - NONE
    image: ${WORKER_TEST_DATA_GENERATOR_IMAGE}
    networks:
      platform: null
  worker-timer:
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 128M
        reservations:
          cpus: '0.03'
          memory: 64M
      restart_policy:
        condition: any
        delay: 10s
        window: 120s
    environment:
      FM_CDN_REGISTRY_URL: ${CDN_REGISTRY_URL:-http://cdn-server:4873}
      FM_DATACATALOG_URL: ${DATACATALOG_URL:-http://datacatalog-api:8080}
      FM_ROUTER_TRANSPORT_ADDRESS: tcp://*:5560
      FM_RUNTIME_HTTP_ADDRESS: http://flowmaker-scheduler:3120
      FM_WORKER_ID: worker-timer001
      FM_WORKER_LOG_SOCKET_IO_ENDPOINT: http://flowmaker-logging:3000
      FM_WORKER_TRANSPORT_ADV_ADDRESS: tcp://worker-timer:5560
    healthcheck:
      test:
      - NONE
    image: ${WORKER_TIMER_IMAGE}
    networks:
      platform: null
  worker-timeseries:
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 128M
        reservations:
          cpus: '0.03'
          memory: 64M
      restart_policy:
        condition: any
        delay: 10s
        window: 120s
    environment:
      FM_CDN_REGISTRY_URL: ${CDN_REGISTRY_URL:-http://cdn-server:4873}
      FM_DATACATALOG_URL: ${DATACATALOG_URL:-http://datacatalog-api:8080}
      FM_ROUTER_TRANSPORT_ADDRESS: tcp://*:5560
      FM_RUNTIME_HTTP_ADDRESS: http://flowmaker-scheduler:3120
      FM_WORKER_ID: worker-timeseries001
      FM_WORKER_LOG_SOCKET_IO_ENDPOINT: http://flowmaker-logging:3000
      FM_WORKER_TRANSPORT_ADV_ADDRESS: tcp://worker-timeseries:5560
    healthcheck:
      test:
      - NONE
    image: ${WORKER_TIMESERIES_IMAGE}
    networks:
      platform: null
x-swarm-worker:
  deploy:
    resources:
      limits:
        cpus: '0.25'
        memory: 128M
      reservations:
        cpus: '0.03'
        memory: 64M
    restart_policy:
      condition: any
      delay: 10s
      window: 120s
  healthcheck:
    test:
    - NONE
  networks:
  - platform
x-worker:
  environment:
    FM_CDN_REGISTRY_URL: ${CDN_REGISTRY_URL:-http://cdn-server:4873}
    FM_DATACATALOG_URL: ${DATACATALOG_URL:-http://datacatalog-api:8080}
    FM_ROUTER_TRANSPORT_ADDRESS: tcp://*:5560
    FM_RUNTIME_HTTP_ADDRESS: http://flowmaker-scheduler:3120
    FM_WORKER_LOG_SOCKET_IO_ENDPOINT: http://flowmaker-logging:3000
networks:
  platform:
    external: true
    name: ${ENV}-platform
