networks:
  default:
    name: base_default
  platform:
    external: true
    name: ${ENV}-platform
  traefik-public:
    external: true
    name: traefik-shared_traefik-public
secrets:
  datacatalog_api_key:
    external: true
    name: ${ENV}_datacatalog_api_key
  datacatalog_db_password:
    external: true
    name: ${ENV}_datacatalog_db_password
  grafana_admin_password:
    external: true
    name: ${ENV}_grafana_admin_password
  grafana_db_password:
    external: true
    name: ${ENV}_grafana_db_password
  influx_admin_token:
    external: true
    name: ${ENV}_influx_admin_token
  postgres_admin_password:
    external: true
    name: ${ENV}_postgres_admin_password
services:
  alertmanager:
    command:
    - --config.file=/etc/alertmanager/alertmanager.yml
    - --storage.path=/alertmanager
    - --web.external-url=https://alertmanager.${INDUSTREAM_DOMAIN}
    - --cluster.listen-address=
    deploy:
      labels:
      - traefik.enable=true
      - traefik.http.routers.${ENV}-alertmanager-secure.entrypoints=websecure
      - traefik.http.routers.${ENV}-alertmanager-secure.rule=Host(`alertmanager.${INDUSTREAM_DOMAIN}`)
      - traefik.http.routers.${ENV}-alertmanager-secure.tls=true
      - traefik.http.routers.${ENV}-alertmanager-secure.service=${ENV}-alertmanager
      - traefik.http.routers.${ENV}-alertmanager-secure.middlewares=traefik-auth@file,rate-limit@file,allow-iframe@file
      - traefik.http.routers.${ENV}-alertmanager.entrypoints=web
      - traefik.http.routers.${ENV}-alertmanager.rule=Host(`alertmanager.${INDUSTREAM_DOMAIN}`)
      - traefik.http.routers.${ENV}-alertmanager.middlewares=redirect-to-https@file
      - traefik.http.services.${ENV}-alertmanager.loadbalancer.server.port=9093
      resources:
        limits:
          cpus: '0.1'
          memory: 64M
        reservations:
          cpus: '0.02'
          memory: 32M
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 0
        window: 120s
    image: prom/alertmanager:${ALERTMANAGER_VERSION}
    networks:
      platform: null
      traefik-public: null
    volumes:
    - bind:
        create_host_path: true
      read_only: true
      source: /tmp/iw-port/unified/base/config/alertmanager
      target: /etc/alertmanager
      type: bind
    - source: alertmanager-data
      target: /alertmanager
      type: volume
      volume: {}
  cadvisor:
    command:
    - --housekeeping_interval=30s
    - --disable_metrics=disk,diskIO,tcp,udp,percpu,sched,process
    - --store_container_labels=true
    - --docker_only=true
    - --containerd=/run/containerd/containerd.sock
    - --containerd-namespace=moby
    deploy:
      mode: global
      resources:
        limits:
          cpus: '0.5'
          memory: 128M
        reservations:
          cpus: '0.08'
          memory: 64M
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 0
        window: 120s
    image: ${CADVISOR_IMAGE}:${CADVISOR_VERSION}
    networks:
      platform: null
    volumes:
    - bind:
        create_host_path: true
        propagation: rslave
      read_only: true
      source: /
      target: /rootfs
      type: bind
    - bind:
        create_host_path: true
      source: /var/run
      target: /var/run
      type: bind
    - bind:
        create_host_path: true
      read_only: true
      source: /var/run/docker.sock
      target: /var/run/docker.sock
      type: bind
    - bind:
        create_host_path: true
      read_only: true
      source: /run/containerd/containerd.sock
      target: /run/containerd/containerd.sock
      type: bind
    - bind:
        create_host_path: true
      read_only: true
      source: /sys
      target: /sys
      type: bind
    - bind:
        create_host_path: true
      read_only: true
      source: /sys/fs/cgroup
      target: /sys/fs/cgroup
      type: bind
    - bind:
        create_host_path: true
      read_only: true
      source: /dev/disk/
      target: /dev/disk
      type: bind
    - bind:
        create_host_path: true
      read_only: true
      source: /var/lib/docker/
      target: /var/lib/docker
      type: bind
  grafana:
    deploy:
      labels:
      - traefik.enable=true
      - traefik.http.routers.${ENV}-grafana-secure.entrypoints=websecure
      - traefik.http.routers.${ENV}-grafana-secure.rule=Host(`grafana-direct.${INDUSTREAM_DOMAIN}`)
      - traefik.http.routers.${ENV}-grafana-secure.tls=true
      - traefik.http.routers.${ENV}-grafana-secure.service=${ENV}-grafana
      - traefik.http.routers.${ENV}-grafana-secure.middlewares=allow-iframe@file
      - traefik.http.routers.${ENV}-grafana.entrypoints=web
      - traefik.http.routers.${ENV}-grafana.rule=Host(`grafana-direct.${INDUSTREAM_DOMAIN}`)
      - traefik.http.routers.${ENV}-grafana.middlewares=redirect-to-https@file
      - traefik.http.services.${ENV}-grafana.loadbalancer.server.port=3000
      - traefik.http.routers.${ENV}-grafana-live-secure.entrypoints=websecure
      - traefik.http.routers.${ENV}-grafana-live-secure.rule=Host(`dashboard.${INDUSTREAM_DOMAIN}`)
        && PathPrefix(`/grafana/api/live`)
      - traefik.http.routers.${ENV}-grafana-live-secure.tls=true
      - traefik.http.routers.${ENV}-grafana-live-secure.service=${ENV}-grafana
      - traefik.http.routers.${ENV}-grafana-live-secure.middlewares=allow-iframe@file
      - traefik.http.routers.${ENV}-grafana-live-secure.priority=200
      resources:
        limits:
          cpus: '0.5'
          memory: 1024M
        reservations:
          cpus: '0.08'
          memory: 256M
      restart_policy:
        condition: any
        delay: 10s
        max_attempts: 0
        window: 120s
    environment:
    - TERM=linux
    - GF_DEFAULT_APP_MODE=${GF_APP_MODE}
    - GF_LOG_LEVEL=${GF_LOG_LEVEL}
    - GF_DATAPROXY_LOGGING=true
    - GF_AUTH_ANONYMOUS_ENABLED=false
    - GF_AUTH_BASIC_ENABLED=false
    - GF_AUTH_DISABLE_LOGIN_FORM=true
    - GF_AUTH_DISABLE_SIGNOUT_MENU=false
    - GF_AUTH_LOGIN_COOKIE_NAME=grafana_session
    - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER}
    - GF_SECURITY_ADMIN_PASSWORD__FILE=/run/secrets/${GRAFANA_ADMIN_PASSWORD_SECRET_NAME}
    - GF_FEATURE_TOGGLES_ENABLE=accessControlOnCall,idForwarding,externalServiceAccounts
    - GF_ALERTING_ENABLED=false
    - GF_UNIFIED_ALERTING_ENABLED=false
    - GF_LOG_FILTERS=plugin.mahendrapaipuri-dashboardreporter-app:debug
    - GF_SECURITY_ALLOW_EMBEDDING=true
    - GF_SERVER_SERVE_FROM_SUB_PATH=true
    - GF_SERVER_ROOT_URL=https://dashboard.${INDUSTREAM_DOMAIN}/grafana/
    - GF_DATABASE_TYPE=postgres
    - GF_DATABASE_HOST=${GRAFANA_DB_HOST}:5432
    - GF_DATABASE_NAME=${GRAFANA_DB_NAME}
    - GF_DATABASE_USER=${GRAFANA_DB_USER}
    - GF_DATABASE_PASSWORD__FILE=/run/secrets/${GRAFANA_DB_PASSWORD_SECRET_NAME}
    - GF_DATABASE_SSL_MODE=${GF_DATABASE_SSL_MODE}
    - TZ=${TZ}
    - GF_INSTALL_PLUGINS=yesoreyeram-infinity-datasource,marcusolsson-json-datasource,volkovlabs-echarts-panel${GRAFANA_DATABRIDGE_PLUGIN}
    - GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS=industream-databridge-datasource,industream-hubbridge-app
    - GF_LIVE_MAX_CONNECTIONS=0
    - INDUSTREAM_DOMAIN=${INDUSTREAM_DOMAIN}
    - GF_AUTH_JWT_ENABLED=true
    - GF_AUTH_JWT_ENABLE_LOGIN_TOKEN=true
    - GF_AUTH_JWT_HEADER_NAME=Authorization
    - GF_AUTH_JWT_URL_LOGIN=true
    - GF_AUTH_JWT_JWK_SET_URL=https://${INDUSTREAM_DOMAIN}/api/uifusion/auth/jwks
    - GF_AUTH_JWT_TLS_SKIP_VERIFY_INSECURE=false
    - GF_AUTH_JWT_EXPECT_CLAIMS={"iss":"hub-backend","aud":"industream-hub"}
    - GF_AUTH_JWT_USERNAME_CLAIM=sub
    - GF_AUTH_JWT_EMAIL_CLAIM=email
    - GF_AUTH_JWT_AUTO_SIGN_UP=true
    - GF_AUTH_JWT_ROLE_ATTRIBUTE_PATH=contains(roles, 'admin') && 'Admin' || 'Editor'
    - INFLUX_BUCKET=${INFLUX_BUCKET}
    - INFLUX_ORG=${INFLUX_ORG}
    - DATACATALOG_DB_USER=${DATACATALOG_DB_USER}
    - POSTGRES_ADMIN_USER=${POSTGRES_ADMIN_USER}
    - SSL_CERT_FILE=/etc/ssl/certs/ca-certificates.crt
    - SSL_CERT_DIR=/etc/grafana/extra-cas
    extra_hosts:
    - ${INDUSTREAM_DOMAIN}:host-gateway
    healthcheck:
      interval: 30s
      retries: 3
      start_period: 40s
      test:
      - CMD-SHELL
      - wget --no-verbose --tries=1 --spider http://localhost:3000/api/health || exit
        1
      timeout: 10s
    image: grafana/grafana-oss:${GRAFANA_VERSION}
    networks:
      platform: null
      traefik-public: null
    secrets:
    - source: grafana_admin_password
      target: ${ENV}_grafana_admin_password
    - source: grafana_db_password
      target: ${ENV}_grafana_db_password
    - source: influx_admin_token
      target: ${ENV}_influx_admin_token
    - source: datacatalog_db_password
      target: ${ENV}_datacatalog_db_password
    - source: postgres_admin_password
      target: ${ENV}_postgres_admin_password
    - source: datacatalog_api_key
      target: datacatalog_api_key
    volumes:
    - bind:
        create_host_path: true
      read_only: true
      source: /tmp/iw-port/unified/base/config/grafana/provisioning
      target: /etc/grafana/provisioning
      type: bind
    - bind:
        create_host_path: true
      read_only: true
      source: /tmp/iw-port/unified/base/config/grafana/plugins/industream-hubbridge-app
      target: /var/lib/grafana/plugins/industream-hubbridge-app
      type: bind
    - source: grafana-data
      target: /var/lib/grafana
      type: volume
      volume: {}
    - bind:
        create_host_path: true
      read_only: true
      source: /tmp/iw-port/unified/base/certs/${INDUSTREAM_DOMAIN}.crt
      target: /etc/grafana/extra-cas/platform.crt
      type: bind
  grafana-wrapper:
    deploy:
      labels:
      - traefik.enable=true
      - traefik.http.routers.${ENV}-grafana-wrapper-secure.entrypoints=websecure
      - traefik.http.routers.${ENV}-grafana-wrapper-secure.rule=Host(`dashboard.${INDUSTREAM_DOMAIN}`)
      - traefik.http.routers.${ENV}-grafana-wrapper-secure.tls=true
      - traefik.http.routers.${ENV}-grafana-wrapper-secure.service=${ENV}-grafana-wrapper
      - traefik.http.routers.${ENV}-grafana-wrapper-secure.middlewares=allow-iframe@file
      - traefik.http.routers.${ENV}-grafana-wrapper.entrypoints=web
      - traefik.http.routers.${ENV}-grafana-wrapper.rule=Host(`dashboard.${INDUSTREAM_DOMAIN}`)
      - traefik.http.routers.${ENV}-grafana-wrapper.middlewares=redirect-to-https@file
      - traefik.http.services.${ENV}-grafana-wrapper.loadbalancer.server.port=8080
      resources:
        limits:
          cpus: '0.1'
          memory: 64M
        reservations:
          cpus: '0.01'
          memory: 16M
      restart_policy:
        condition: any
        delay: 5s
        window: 120s
    environment:
    - INDUSTREAM_HUB_ORIGIN=${INDUSTREAM_HUB_ORIGIN}
    healthcheck:
      interval: 30s
      retries: 3
      start_period: 10s
      test:
      - CMD-SHELL
      - wget --no-verbose --tries=1 --spider http://127.0.0.1:8080/ || exit 1
      timeout: 5s
    image: ${GRAFANA_WRAPPER_IMAGE}
    networks:
      platform: null
      traefik-public: null
  node-exporter:
    command:
    - --path.procfs=/host/proc
    - --path.sysfs=/host/sys
    - --path.rootfs=/host
    - --collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)
    deploy:
      mode: global
      resources:
        limits:
          cpus: '0.1'
          memory: 64M
        reservations:
          cpus: '0.02'
          memory: 32M
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 0
        window: 120s
    image: prom/node-exporter:${NODE_EXPORTER_VERSION}
    networks:
      platform: null
    volumes:
    - bind:
        create_host_path: true
      read_only: true
      source: /proc
      target: /host/proc
      type: bind
    - bind:
        create_host_path: true
      read_only: true
      source: /sys
      target: /host/sys
      type: bind
    - bind:
        create_host_path: true
        propagation: rslave
      read_only: true
      source: /
      target: /host
      type: bind
  postgres-exporter:
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 64M
        reservations:
          cpus: '0.02'
          memory: 32M
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 0
        window: 120s
    environment:
    - DATA_SOURCE_URI=${POSTGRES_EXPORTER_DB_HOST}:5432/postgres?sslmode=disable
    - DATA_SOURCE_USER=${POSTGRES_ADMIN_USER}
    - DATA_SOURCE_PASS_FILE=/run/secrets/${POSTGRES_ADMIN_PASSWORD_SECRET_NAME}
    - PG_EXPORTER_DISABLE_DEFAULT_METRICS=false
    - PG_EXPORTER_DISABLE_SETTINGS_METRICS=false
    image: prometheuscommunity/postgres-exporter:${POSTGRES_EXPORTER_VERSION}
    networks:
      platform: null
    secrets:
    - source: postgres_admin_password
      target: ${ENV}_postgres_admin_password
  prometheus:
    command:
    - --config.file=/etc/prometheus/prometheus.yml
    - --storage.tsdb.path=/prometheus
    - --storage.tsdb.retention.time=30d
    - --web.console.libraries=/usr/share/prometheus/console_libraries
    - --web.console.templates=/usr/share/prometheus/consoles
    - --web.external-url=https://prometheus.${INDUSTREAM_DOMAIN}
    deploy:
      labels:
      - traefik.enable=true
      - traefik.http.routers.${ENV}-prometheus-secure.entrypoints=websecure
      - traefik.http.routers.${ENV}-prometheus-secure.rule=Host(`prometheus.${INDUSTREAM_DOMAIN}`)
      - traefik.http.routers.${ENV}-prometheus-secure.tls=true
      - traefik.http.routers.${ENV}-prometheus-secure.service=${ENV}-prometheus
      - traefik.http.routers.${ENV}-prometheus-secure.middlewares=traefik-auth@file,rate-limit@file,allow-iframe@file
      - traefik.http.routers.${ENV}-prometheus.entrypoints=web
      - traefik.http.routers.${ENV}-prometheus.rule=Host(`prometheus.${INDUSTREAM_DOMAIN}`)
      - traefik.http.routers.${ENV}-prometheus.middlewares=redirect-to-https@file
      - traefik.http.services.${ENV}-prometheus.loadbalancer.server.port=9090
      resources:
        limits:
          cpus: '1.0'
          memory: 768M
        reservations:
          cpus: '0.08'
          memory: 256M
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 0
        window: 120s
    extra_hosts:
    - host.docker.internal:host-gateway
    healthcheck:
      interval: 30s
      retries: 3
      start_period: 30s
      test:
      - CMD-SHELL
      - wget --spider -q http://localhost:9090/-/ready || exit 1
      timeout: 10s
    hostname: prometheus
    image: prom/prometheus:${PROMETHEUS_VERSION}
    networks:
      platform: null
      traefik-public: null
    volumes:
    - bind:
        create_host_path: true
      read_only: true
      source: /tmp/iw-port/unified/base/config/prometheus/prometheus.yml
      target: /etc/prometheus/prometheus.yml
      type: bind
    - bind:
        create_host_path: true
      read_only: true
      source: /tmp/iw-port/unified/base/config/prometheus/rules
      target: /etc/prometheus/rules
      type: bind
    - source: prometheus-data
      target: /prometheus
      type: volume
      volume: {}
volumes:
  alertmanager-data:
    name: ${ENV}-alertmanager-data
  grafana-data:
    name: ${ENV}-grafana-data
  prometheus-data:
    name: ${ENV}-prometheus-data
